### ISSUE TITLE
Discord trigger - Bot didn't receive message from channel

### ISSUE THREAD

**Issue by waaman** [hckdotng/n8n-nodes-discord#1]
Hello,

First of all thank you for providing this node.

i'm testing your node and i'm faced of problem for getting discord's channel to n8n node message.
The bot is online in my discord channel, the Discord send works well but i can't receive message from channel.

I saw the webhook part on the Discord Trigger parameter page ans when i go to it:
`{"code":404,"message":"The requested webhook \"GET 4bb4bcad-c953-4de0-ad06-xxxxxx/webhook\" is not registered.","hint":"The workflow must be active for a production URL to run successfully. You can activate the workflow using the toggle in the top-right of the editor. Note that unlike test URL calls, production URL calls aren't shown on the canvas (only in the executions list)"}`

I'm confused so i don't know if this message is relveant.

Have you some hints for me to solve this ?

Regards,

I'm french

**Comment by hckdotng** [comment]
Hi, are you using the last version and have you configured the base url in the credentials?
What do you mean "when I got to it"? Can you provide a screenshot maybe?
The discord trigger use a POST webhook internally (that's how the bot start a workflow when a message match what you have set), the URL is registered when you create/update the trigger. It uses the base url and need to be reachable from outside.
Don't hesitate to join me on Discord: keras#0724

**Comment by waaman** [comment]
Thx for your answer.

"[...]It uses the base url and need to be reachable from outside.[...]"
I have set same data than n8n API credential that said "success" so i suppose it is ok.

I sent you a discord invite.

**Comment by waaman** [comment]
Thank you very much for your help on discord.

After a fresh install of n8n docker container and configuration for the POST base url without custom port and through a proxy manager it's working.

**Comment by Santofer** [comment]
Hello, and thank you for this wonderful node. I have the same problem, n8n just keeps Listening for a trigger event even though everything is set up the right way. Can you please help?

**Comment by hckdotng** [comment]
@Santofer Hello, please open a new issue and add more details (version of the node & n8n, logs when an event is supposed to trigger your workflow, configuration of your trigger, if the trigger is active, bot online, if the webhook url is reachable...).
