### ISSUE TITLE
Listening for a trigger event not receiving any command

### ISSUE THREAD

**Issue by Santofer** [hckdotng/n8n-nodes-discord#12]
Hi, thanks for the amazing node.

But in my case, it just keeps listening without any command being received despite the fact that it connects perfectly to my discord. Using v0.4.2 of n8n-nodes-discord with a self-hosted instance of n8n (Version 0.209.3) running on Docker in my own Synology server.

Here's the log, can you please help me with this?

<img width="1089" alt="Screenshot 2022-12-28 at 19 09 25" src="https://user-images.githubusercontent.com/73022401/209855086-6fc8a761-f0a2-42cd-88be-c20724f9bcaf.png">

**Comment by hckdotng** [comment]
Hi, is the trigger active and the bot appears online? Is the webhook url reachable when you call it with a REST client?
Can you provide the configuration of your trigger (a screenshot of the node UI)?

**Comment by Santofer** [comment]
Yes both the trigger active and bot online. And I sent an http request to the webhook url to get all the workflows that succeeded.


<img width="712" alt="Screenshot 2022-12-29 at 11 29 00" src="https://user-images.githubusercontent.com/73022401/209939862-4fc9e885-37e5-4074-a8a2-4da75a28614d.png">
<img width="330" alt="Screenshot 2022-12-29 at 11 29 07" src="https://user-images.githubusercontent.com/73022401/209939884-62ef5910-5b80-4516-ad96-7d37d9aab4c1.png">
<img width="1187" alt="Screenshot 2022-12-29 at 11 40 12" src="https://user-images.githubusercontent.com/73022401/209939890-cde2b7b8-b5d9-4445-b7b2-7cb60765ee2a.png">
<img width="145" alt="Screenshot 2022-12-29 at 11 28 35" src="https://user-images.githubusercontent.com/73022401/209939898-4eaa40de-108d-42ff-b40a-685b90f64b5e.png">

**Comment by hckdotng** [comment]
If you modify your trigger and save it, did you see in your logs a related event? (received event of : trigger, trigger xxxxx update)

The problem could be that the bot is not aware of the existence of the trigger.

I tested the node with the last version of n8n (0.209.x), it seems ok.

**Comment by Santofer** [comment]
In the log I can see it's received credentials and list:roles only.

**Comment by Santofer** [comment]
I needed to activate the node for it to work. Problem solved and thank you for your support on Discord.
