### ISSUE TITLE
Credentials error

### ISSUE THREAD

**Issue by harleckinz** [hckdotng/n8n-nodes-discord#21]
Hi! Unfortunately I can't set up an SSL, because of the current DDNS provider. I cannot use several N8N nodes, like Gmail, etc. And now I've got a Credential error with this node. There are any way to get this works without SSL?

(SSL in the n8n instance's address)

Thanks a lot!

**Comment by edbrdi** [comment]
Hi, can you provide more info about the credential error?

**Comment by harleckinz** [comment]
Hi! 

Thanks for the quick reply! 

So the node keeps logging in and there is an error in the n8n logs: (I tried with api/v1/ too.)

<img width="481" alt="2023-01-29_09h31_44" src="https://user-images.githubusercontent.com/25708009/215315090-840afe8f-f72e-4bd0-ade9-7655579b30e9.png">
<img width="554" alt="2023-01-29_09h33_19" src="https://user-images.githubusercontent.com/25708009/215315094-63b3b94c-9144-4f1b-b64f-bfb5a65c1cf0.png">

**Comment by edbrdi** [comment]
The baseUrl must end with /api/v1, /api/v1/docs is the swagger documentation.
Anyway, the problem here seems to be the bot connection, you may want to check if your clientId & token are correct.

**Comment by harleckinz** [comment]
Hi! 

Thank you for helping me out with this!

I made a mistake because I used an already made bot and customized for that task. That was it's problem.
