### ISSUE TITLE
"Discord Send" node missing after 0.216.0+

### ISSUE THREAD

**Issue by dreamerc** [hckdotng/n8n-nodes-discord#23]
After version 0.216.0, the interface underwent numerous changes. 
The 'Add node' feature is not functional, and it will bring the trigger, 'Discord Trigger' instead. 

The last workable version is 0.215.3. 
A workaround is to import from the old version and duplicate the node.

**Comment by thefourcraft** [comment]
Yep, I also noticed this issue, which resulted in a complete failure of my n8n workflows 😆 
they maybe changed something in the 0.216.0 update

**Comment by thefourcraft** [comment]
@dreamerc, it's fixed update your n8n to the latest update!

**Comment by dreamerc** [comment]
Great :+1:
