### ISSUE TITLE
enhancement - add more data on trigger output

### ISSUE THREAD

**Issue by waaman** [hckdotng/n8n-nodes-discord#3]
Hello. Thank you for your work.

Actually the trigger output 3 fields: content, channelid and userid.

For example if i need the username i send a local http request to an api client so i guess i can deal with that but if i want to deal with the initial message id that trigger the event i'm stuck.

Perhaps i don't really know how to do that correctly but do you think that'll be possible to add more fields on the trigger output in the future ?

Like 'messageid', 'sendername' something like that ?

Regards,

**Comment by hckdotng** [comment]
Hi, yes I can add more context regarding the triggering message/user, probably in the next update.

**Comment by waaman** [comment]
Thank you,

**Comment by hckdotng** [comment]
I've updated the nodes, more context is now available. You can find details in the [readme](https://github.com/hckdotng/n8n-nodes-discord#readme) - "Returned data" section of each node.
