### ISSUE TITLE
I need your help 

### ISSUE THREAD

**Issue by YDeltagon** [hckdotng/n8n-nodes-discord#5]
![image](https://user-images.githubusercontent.com/70691658/200907501-a93b29f8-d5de-4a4c-ba96-f13186803bf9.png)
![image](https://user-images.githubusercontent.com/70691658/200907512-a0b20ac4-e6b8-43fc-ab13-b78fba2a9055.png)
![image](https://user-images.githubusercontent.com/70691658/200907519-0158721a-c4d8-4d8c-adb6-897ee77ecc01.png)

**Hello, thanks for your time, and your project**
Here, I manage with all this to send messages, but impossible to ensure that it arrives at trigger from a discord message, it remains pending
Moreover, the BOT seems offline when my workflow is activated, I don't know how to do it

**Comment by waaman** [comment]
Hi.
You can test if your discord bot is online sending on a channel where he is: /test True

This slash command must disappear if your bot is listening. In "test" mode you can click the "Execute Workflow" on your workflow for testing.

If your bot is not connected at all you must use the top right corner button "Active".

After all see your logs too.

**Comment by hckdotng** [comment]
Hi, could you provide more details (n8n version, n8n-nodes-discord version, server logs starting when you active the workflow)?

**Comment by YDeltagon** [comment]
I don't no why, but, today, it's work fine...
Yesterday, I reinstalled everything, redid everything, tried to /test, activate the flow, run the workflow, but nothing happened

I just started my PC, test, it's OK

Thank you for your time, sorry it's my fault, have a nice day
