### ISSUE TITLE
More than 1 output?

### ISSUE THREAD

**Issue by TheSmilez** [hckdotng/n8n-nodes-discord#6]
Hey man, first things first, thank you for making this. It's made my life so much easier. Amazing work! I was wondering if there is a way to send more than one output at a time? For example...

I have 5 objects that would normally be passed through as webhooks to their appropriate channels, but your bot only sends out the first object instead of each item. Is there something I'm doing wrong or is that not implemented yet? Thanks in advance! Cheers.

Here's a couple screenshots of my work flow and what's coming in / out.
![brave_yGXGYqDZYr](https://user-images.githubusercontent.com/52396069/204519013-0e5bdccb-be4e-4871-a570-ba5523fd19b5.png)
![brave_jvuRnC4FPY](https://user-images.githubusercontent.com/52396069/204519048-2c252441-0aad-427a-873b-fcd67a9d2dd5.png)

**Comment by hckdotng** [comment]
Hi, thanks, Nodes usually handle multiple items automatically, I didn't loop over all items but I can definitely improve this.

Until I update the node in a next release, maybe you could use "split in batches" to create a loop : https://docs.n8n.io/integrations/builtin/core-nodes/n8n-nodes-base.splitinbatches/ - https://docs.n8n.io/flow-logic/looping/

**Comment by TheSmilez** [comment]
> Hi, thanks, Nodes usually handle multiple items automatically, I didn't loop over all items but I can definitely improve this.
> 
> Until I update the node in a next release, maybe you could use "split in batches" to create a loop : https://docs.n8n.io/integrations/builtin/core-nodes/n8n-nodes-base.splitinbatches/ - https://docs.n8n.io/flow-logic/looping/

Awesome thanks for the response! Cheers!
